import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  cameraContainer: {
    flex: 0.8,
    justifyContent: "center",
    alignItems: "center",
  },
  targetBox: {
    width: 250,
    height: 120,
    borderWidth: 2,
    borderColor: "#00FF00",
    borderRadius: 8,
  },
  painelVenda: {
    flex: 1.7,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 120,
  },
  inputRow: { flexDirection: "row", alignItems: "center", marginBottom: 15 },
  label: { fontSize: 18, fontWeight: "bold" },
  titulo: { fontSize: 20, fontWeight: "bold", marginBottom: 10 },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
    width: 60,
    marginLeft: 10,
    fontSize: 18,
    textAlign: "center",
  },
  totalHeader: {
    fontSize: 20,
    fontWeight: "bold",
    marginLeft: "auto",
    color: "#2E7D32",
  },
  headerCarrinho: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  btnCancelar: {
    color: "#d32f2f",
    fontSize: 14,
    textDecorationLine: "underline",
  },
  btnRemoverItem: {
    backgroundColor: "#ffebee",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    justifyContent: "center",
  },
  btnRemoverTexto: {
    color: "#d32f2f",
    fontSize: 12,
    fontWeight: "bold",
  },
  lista: { flex: 1, marginVertical: 10 },
  itemCarrinho: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    alignItems: "center",
  },
  itemNome: { fontSize: 16 },
  itemPreco: { fontSize: 16, fontWeight: "bold" },
  btnFinalizar: {
    backgroundColor: "#2E7D32",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
  },
  btnTexto: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  message: { color: "#fff", textAlign: "center", marginBottom: 20 },
  flashOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,255,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  flashText: { color: "#fff", fontSize: 30, fontWeight: "bold" },
});
